// Generated by scripts/build-content.js. Do not edit the bundle directly.
// ---- src/striffs-core.js ----
// Striffs — core (state, logging, messaging, storage, languages)
(() => {
  const S = (window.Striffs = window.Striffs || {});

  // ---------- Constants / State ----------
  S.MAX_UNAUTH_ZIP_SIZE_MB = 50;
  S.CACHE_TTL_MS = 24 * 60 * 60 * 1000; // 24h
  S.TIMEOUTS = Object.freeze({
    message: 7000,
    ping: 1000,
    getLanguages: 12000,
    waitForToolbar: 8000,
    bgGenerate: 180000,
    bgToken: 180000,
  });

  S.__striffsSvg = null;
  S.__striffsPanzoom = null;
  S.__striffsPathToComponentId = new Map();
  S.__striffsComponentIdToFile = new Map();
  S.__filePathToDiffId = new Map(); // "/path" -> diffId (no '#')
  S.__striffsReady = false;
  S.__lastFetchedUpdatedAt = null;
  S.__styleInjected = false;

  // ---------- Logging ----------
  S.clog = (...a) => { try { console.log('[Striffs]', ...a); } catch { } };
  S.cinfo = (...a) => { try { console.info('[Striffs]', ...a); } catch { } };
  S.cwarn = (...a) => { try { console.warn('[Striffs]', ...a); } catch { } };
  S.cerr = (...a) => { try { console.error('[Striffs]', ...a); } catch { } };

  // ---------- API base override helpers (for testing) ----------
  S.setApiBaseOverride = async (base) => new Promise((resolve) => {
    try {
      if (chrome?.storage?.local) {
        chrome.storage.local.set({ striffsApiBase: base }, () => resolve(true));
      } else {
        resolve(false);
      }
    } catch {
      resolve(false);
    }
  });

  S.clearApiBaseOverride = async () => new Promise((resolve) => {
    try {
      if (chrome?.storage?.local) {
        chrome.storage.local.remove('striffsApiBase', () => resolve(true));
      } else {
        resolve(false);
      }
    } catch {
      resolve(false);
    }
  });

  // ---------- Utils ----------
  S.sleep = (ms) => new Promise(r => setTimeout(r, ms));

  // ---------- Cache clearing (per-page) ----------
  S.clearLocalDiagramCaches = () => {
    const prefixes = ["striffs:", "StriffsCache:"];
    const clearStore = (store) => {
      if (!store || typeof store.length !== "number") return;
      const toRemove = [];
      for (let i = 0; i < store.length; i++) {
        const key = store.key(i);
        if (key && prefixes.some(p => key.startsWith(p))) toRemove.push(key);
      }
      toRemove.forEach(k => { try { store.removeItem(k); } catch {} });
    };
    try { clearStore(window.localStorage); } catch {}
    try { clearStore(window.sessionStorage); } catch {}

    S.__striffsReady = false;
    S.__striffsSvg = null;
    S.__striffsPanzoom = null;
    S.__striffsPathToComponentId?.clear?.();
    S.__striffsComponentIdToFile?.clear?.();
    S.__filePathToDiffId?.clear?.();
    S.state?.resetPanState?.();
    S.state?.resetInitialFit?.();
    S.state?.resetTooLarge?.();
  };

  if (chrome?.runtime?.onMessage?.addListener) {
    chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
      if (msg?.type === "clearStriffsCaches") {
        try { S.clearLocalDiagramCaches(); } catch {}
        try { S.showDiffView?.(); } catch {}
        sendResponse?.({ ok: true });
      }
    });
  }

  // ---------- Messaging (MV3-hardened) ----------
  S.sendMessageWithTimeout = function sendMessageWithTimeout(msg, timeoutMs = 7000) {
    return new Promise((resolve, reject) => {
      let settled = false;
      const t = setTimeout(() => {
        if (!settled) {
          settled = true;
          reject(new Error(`timeout after ${timeoutMs}ms`));
        }
      }, timeoutMs);

      try {
        chrome.runtime.sendMessage(msg, (resp) => {
          if (settled) return;
          settled = true;
          clearTimeout(t);
          if (chrome.runtime.lastError) {
            reject(new Error(chrome.runtime.lastError.message));
          } else if (resp == null || (typeof resp !== 'object' && typeof resp !== 'boolean')) {
            reject(new Error('empty/invalid response from background'));
          } else {
            resolve(resp);
          }
        });
      } catch (e) {
        if (settled) return;
        settled = true;
        clearTimeout(t);
        reject(new Error(String(e?.message || e)));
      }
    });
  };

  S.waitForBackgroundReady = async function waitForBackgroundReady({ attempts = 5, delayMs = 150 } = {}) {
    let d = delayMs;
    for (let i = 0; i < attempts; i++) {
      try {
        const r = await S.sendMessageWithTimeout({ type: 'ping' }, S.TIMEOUTS.ping);
        if (r?.ok) return true;
      } catch {
        // fall through to retry
      }
      await S.sleep(d);
      d = Math.min(Math.floor(d * 1.8), 1200);
    }
    return false;
  };

  S.bgRequest = async function bgRequest(msg, timeoutMs) {
    const retryable = (errMsg) =>
      /timeout|port closed|Receiving end does not exist|No service worker/i.test(String(errMsg || ''));

    const send = async () => {
      const resp = await S.sendMessageWithTimeout(msg, timeoutMs ?? S.TIMEOUTS.message);
      if (resp?.ok === true || resp?.success === true) return resp;
      throw new Error(resp?.error || 'background request failed');
    };

    try {
      return await send();
    } catch (err) {
      const errMsg = err?.message || err;
      if (retryable(errMsg)) {
        await S.waitForBackgroundReady({ attempts: 4, delayMs: 150 });
        return await send();
      }
      throw err;
    }
  };

  S.getStoredToken = async () => {
    try {
      const l = await chrome.storage.local.get(["ghToken"]);
      if (l && l.ghToken) return l.ghToken;
    } catch { }
    try {
      const s = await chrome.storage.sync.get(["ghToken"]);
      if (s && s.ghToken) return s.ghToken;
    } catch { }
    return null;
  };

  // ---------- Languages via background ----------
  let __cachedExts = null;

  S.parseLangsToExts = (text) => {
    const langs = String(text || '').split(',').map(s => s.trim().toLowerCase()).filter(Boolean);
    const langToExt = {
      java: "java", golang: "go", go: "go", javascript: "js", typescript: "ts", python: "py",
      csharp: "cs", cpp: "cpp", cplusplus: "cpp", ruby: "rb", rust: "rs", php: "php", kotlin: "kt"
    };
    return langs.map(l => langToExt[l]).filter(Boolean);
  };

  S.fetchSupportedExtensions = async () => {
    if (Array.isArray(__cachedExts)) return __cachedExts;
    await S.waitForBackgroundReady({ attempts: 5, delayMs: 150 });
    try {
      const resp = await S.bgRequest({ type: 'getLanguages' }, S.TIMEOUTS.getLanguages);
      const text = resp.body ?? resp.text ?? '';
      const exts = S.parseLangsToExts(text);
      __cachedExts = exts;
      S.cinfo('Supported extensions:', exts);
      return exts;
    } catch (err) {
      S.cwarn('getLanguages failed:', err?.message || err);
      return [];
    }
  };
})();


// ---- src/striffs-state.js ----
// Striffs — shared state (pan/zoom, fits, storage)
(() => {
  const S = (window.Striffs = window.Striffs || {});

  const validPan = (v) =>
    v && typeof v === 'object' &&
    Number.isFinite(v.x) && Number.isFinite(v.y) && Number.isFinite(v.scale);

  const storageKey = () => {
    try {
      if (typeof S.cacheKey === 'function') {
        return `${S.cacheKey()}:pan`;
      }
    } catch {}
    return null;
  };

  const state = {
    pan: null,
    panDirty: false,
    initialFitDone: false,
    tooLarge: false
  };

  const api = {
    getPanState() {
      if (validPan(state.pan)) return state.pan;
      const key = storageKey();
      if (!key) return null;
      try {
        const raw = localStorage.getItem(key);
        if (!raw) return null;
        const parsed = JSON.parse(raw);
        if (validPan(parsed)) {
          state.pan = parsed;
          return state.pan;
        }
      } catch {}
      return null;
    },

    setPanState(pan) {
      if (!validPan(pan)) return;
      state.pan = pan;
      state.panDirty = true;
    },

    persistPanState() {
      if (!validPan(state.pan)) return;
      const key = storageKey();
      if (!key) return;
      try {
        localStorage.setItem(key, JSON.stringify(state.pan));
        state.panDirty = false;
      } catch {}
    },

    resetPanState() {
      state.pan = null;
      state.panDirty = false;
    },

    isInitialFitDone() {
      return state.initialFitDone;
    },

    markInitialFitDone() {
      state.initialFitDone = true;
    },

    resetInitialFit() {
      state.initialFitDone = false;
    },

    isPanDirty() {
      return state.panDirty;
    },

    setTooLarge(flag) {
      state.tooLarge = !!flag;
    },

    isTooLarge() {
      return !!state.tooLarge;
    },

    resetTooLarge() {
      state.tooLarge = false;
    }
  };

  S.state = S.state || api;
})();


// ---- src/striffs-dom-ui.js ----
// Striffs — DOM & UI
(() => {
    const S = (window.Striffs = window.Striffs || {});
    const { cwarn } = S;

    S.__lastStriffsButtonState = S.__lastStriffsButtonState || null;
    S.__supportedExtensionsForUi = S.__supportedExtensionsForUi || null;
    const State = S.state;

    // Observers keep buttons/files in sync with GitHub's dynamic PR UIs.
    let toolbarObserver = null;
    let toolbarMountScheduled = false;
    let filesObserver = null;
    let filesCheckScheduled = false;

    S.isElementVisible = S.isElementVisible || ((el) => {
        try {
            if (!el) return false;
            if (el.offsetWidth > 0 || el.offsetHeight > 0) return true;
            const rect = typeof el.getBoundingClientRect === 'function' ? el.getBoundingClientRect() : null;
            if (rect && rect.width > 0 && rect.height > 0) return true;
            const style = window.getComputedStyle ? window.getComputedStyle(el) : null;
            if (!style) return false;
            if (style.display === 'none' || style.visibility === 'hidden' || Number(style.opacity || '1') === 0) return false;
            return Boolean(rect && (rect.width > 0 || rect.height > 0));
        } catch {
            return false;
        }
    });

    const isToolbarNode = (node) => {
        if (!(node instanceof Element)) return false;
        const selectors = [
            '.pr-toolbar[data-target="diff-layout.diffToolbar"]',
            '.js-pr-toolbar',
            '[data-testid="pr-toolbar"]',
            'div[role="toolbar"][data-view-component="true"]',
            'div[aria-label="Pull request toolbar"]'
        ];
        if (node.matches?.(selectors.join(','))) return true;
        if (selectors.some(sel => node.querySelector?.(sel))) return true;

        const section = node.matches?.('section') ? node : node.querySelector?.('section');
        if (section) {
            const h2 = section.querySelector('h2.sr-only');
            if (h2 && h2.textContent.trim() === 'Pull Request Toolbar') return true;
        }
        return false;
    };

    const scheduleToolbarMount = () => {
        if (toolbarMountScheduled) return;
        toolbarMountScheduled = true;
        requestAnimationFrame(() => {
            toolbarMountScheduled = false;
            S.mountMainBarButtons();
        });
    };

    S.ensureToolbarObserver = () => {
        if (toolbarObserver || typeof MutationObserver !== 'function') return;
        const root = document.documentElement || document.body;
        if (!root) return;
        toolbarObserver = new MutationObserver((mutations) => {
            for (const mut of mutations) {
                if (mut.type !== 'childList') continue;
                for (const node of mut.addedNodes) {
                    if (isToolbarNode(node)) {
                        scheduleToolbarMount();
                        return;
                    }
                }
            }
        });
        toolbarObserver.observe(root, { childList: true, subtree: true });
    };

    const isFilesNode = (node) => {
        if (!(node instanceof Element)) return false;
        const selectors = [
            '#files',
            'div[data-testid="files-changed"]',
            'div[data-view-component="true"][data-testid="pull-requests-files"]',
            'main[aria-label="Content"] #files',
            'div[data-hpc] #files',
            '#pr-file-tree',
            'div[class*="Diff-module__diff"]',
            '.js-diff-progressive-container',
            '[data-testid="file-diff-split"]',
            '[data-testid="file-diff-unified"]',
            'div.js-file[data-file-type="file"]'
        ];
        if (node.matches?.(selectors.join(','))) return true;
        return selectors.some(sel => node.querySelector?.(sel));
    };

    const scheduleFilesCheck = () => {
        if (filesCheckScheduled) return;
        filesCheckScheduled = true;
        requestAnimationFrame(() => {
            filesCheckScheduled = false;
            S.refreshSupportedFilesState?.();
        });
    };

    S.refreshSupportedFilesState = () => {
        if (!Array.isArray(S.__supportedExtensionsForUi) || S.__supportedExtensionsForUi.length === 0) return;
        if (typeof S.getFilesInPR !== 'function' || typeof S.checkIfRelevantFilesExist !== 'function') return;

        const lastState = S.__lastStriffsButtonState || {};
        if (lastState.loading || lastState.success || lastState.failure || S.__striffsReady) return;

        const files = S.getFilesInPR();
        if (!Array.isArray(files) || files.length === 0) return;

        const hasSupported = S.checkIfRelevantFilesExist(files, S.__supportedExtensionsForUi);
        if (hasSupported) {
            if (lastState.disabled || lastState.neutral) {
                S.updateStriffButton({ tooltip: "Click to generate Striffs" });
            }
        } else {
            S.updateStriffButton({ disabled: true, neutral: true, tooltip: "No supported files in PR" });
        }
    };

    S.ensureFilesObserver = () => {
        if (filesObserver || typeof MutationObserver !== 'function') return;
        const root = document.documentElement || document.body;
        if (!root) return;
        filesObserver = new MutationObserver((mutations) => {
            for (const mut of mutations) {
                if (mut.type !== 'childList') continue;
                const nodes = [...mut.addedNodes, ...mut.removedNodes];
                for (const node of nodes) {
                    if (isFilesNode(node)) {
                        scheduleFilesCheck();
                        return;
                    }
                }
            }
        });
        filesObserver.observe(root, { childList: true, subtree: true });
    };

    S.registerSupportedExtensions = (exts = []) => {
        S.__supportedExtensionsForUi = Array.isArray(exts) ? exts : [];
        S.ensureFilesObserver();
        scheduleFilesCheck();
    };

    // Track current view ('diffs' | 'striffs'), scoped + persisted per cacheKey.
    const normalizeView = (view) => (view === 'striffs' ? 'striffs' : 'diffs');
    const viewStorageKey = () => {
        try {
            return typeof S.cacheKey === 'function' ? `${S.cacheKey()}:view` : null;
        } catch {
            return null;
        }
    };
    const persistView = (view) => {
        const key = viewStorageKey();
        if (!key) return;
        try { localStorage.setItem(key, view); } catch {}
    };
    const loadView = () => {
        const key = viewStorageKey();
        if (!key) return null;
        try {
            const raw = localStorage.getItem(key);
            if (!raw) return null;
            return normalizeView(raw);
        } catch {
            return null;
        }
    };
    const initView = () => {
        const initial = normalizeView(loadView() || 'diffs');
        S.__currentView = initial;
        S.currentView = initial;
        S.setActiveButtons?.(initial);
        return initial;
    };

    S.getCurrentView = () => normalizeView(S.__currentView || S.currentView || initView());
    S.setCurrentView = (view) => {
        const normalized = normalizeView(view);
        S.__currentView = normalized;
        S.currentView = normalized;
        persistView(normalized);
        S.setActiveButtons?.(normalized);
        return normalized;
    };
    S.resetCurrentView = () => initView();
    initView();

    // ---------- Pan/zoom state ----------
    S.savePanState = (state) => {
        State?.setPanState?.(state);
    };

    S.persistPanState = () => {
        State?.persistPanState?.();
    };

    S.loadPanState = () => {
        return State?.getPanState?.() || null;
    };

    S.capturePanState = () => {
        try {
            if (!S.__striffsPanzoom || typeof S.__striffsPanzoom.getTransform !== 'function') return;
            const t = S.__striffsPanzoom.getTransform();
            if (!t) return;
            const { x, y, scale } = t;
            if (!Number.isFinite(x) || !Number.isFinite(y) || !Number.isFinite(scale)) return;
            S.savePanState({ x, y, scale });
        } catch (e) {
            cwarn('capturePanState failed', e);
        }
    };

    S.restorePanState = () => {
        try {
            if (!S.__striffsPanzoom) return false;
            const state = S.loadPanState();
            if (!state) return false;
            const { x, y, scale } = state;
            if (!Number.isFinite(x) || !Number.isFinite(y) || !Number.isFinite(scale)) return false;
            S.__striffsPanzoom.zoomAbs(0, 0, scale);
            S.__striffsPanzoom.moveTo(x, y);
            return true;
        } catch (e) {
            cwarn('restorePanState failed', e);
            return false;
        }
    };

    // ---------- DOM utils ----------
    S.$$first = (selectors) => {
        for (const sel of selectors) {
            const el = document.querySelector(sel);
            if (el) return el;
        }
        return null;
    };

    S.$$all = (selectors) => {
        const set = new Set();
        const out = [];
        for (const sel of selectors) {
            document.querySelectorAll(sel).forEach(el => {
                if (!set.has(el)) {
                    set.add(el);
                    out.push(el);
                }
            });
        }
        return out;
    };

    S.waitForFilesRoot = async (maxMs = 15000) => {
        const start = Date.now();
        const candidates = [
            'div[data-view-component="true"][data-testid="pull-requests-files"]',
            'div[data-testid="files-changed"]',
            'div[data-target="diff-layout.sidebarContainer"]',
            'div.diff-sidebar[data-view-component="true"]',
            'file-tree'
        ];
        while (Date.now() - start < maxMs) {
            const el = S.$$first(candidates);
            if (el) return el;
            await S.sleep(250);
        }
        return S.$$first(candidates);
    };

    // ---------- Toolbar discovery ----------
    S.getMainToolbar = () => {
        const selectors = [
            '[data-testid="pr-toolbar"]',
            'div[aria-label="Pull request toolbar"]',
            'div[role="toolbar"][data-view-component="true"]',
            '.pr-toolbar[data-target="diff-layout.diffToolbar"]',
            '.js-pr-toolbar',
        ];

        const seen = new Set();
        const matches = [];
        const push = (el) => {
            if (!el || seen.has(el)) return;
            seen.add(el);
            matches.push(el);
        };

        selectors.forEach(sel => {
            document.querySelectorAll(sel).forEach(push);
        });

        document.querySelectorAll('section').forEach(sec => {
            const h2 = sec.querySelector('h2.sr-only');
            if (h2 && h2.textContent.trim() === 'Pull Request Toolbar') {
                push(sec);
            }
        });

        if (matches.length === 0) return null;

        const visible = matches.filter(S.isElementVisible);
        if (visible.length > 0) {
            return visible[visible.length - 1];
        }

        return matches[matches.length - 1];
    };

    S.getToolbarControlsRow = (toolbarEl) => {
        if (!toolbarEl) return null;

        // Row that contains the "x/x viewed" counter.
        const viewedCount = toolbarEl.querySelector(
            'span[class*="ViewedFileProgress-module__FilesCountText"]'
        );
        if (viewedCount) {
            const row =
                viewedCount.closest('div.d-flex.flex-items-center') ||
                viewedCount.closest('div');
            if (row) return row;
        }

        // Fallbacks: common flex rows in the toolbar
        const legacyRow =
            toolbarEl.querySelector('.flex-auto.min-width-0 > .d-flex.flex-items-center.flex-wrap') ||
            toolbarEl.querySelector('.diffbar .d-flex.flex-items-center.flex-wrap') ||
            toolbarEl.querySelector('[data-view-component="true"].d-flex.flex-items-center.flex-wrap') ||
            toolbarEl.querySelector('.d-flex.flex-items-center.flex-wrap');
        if (legacyRow) return legacyRow;

        // Final fallback: the toolbar root
        return toolbarEl;
    };

    // ---------- Octicons & Buttons ----------
    S.octicon = function octicon(name) {
        const pathMap = {
            file: 'M3 2.75A.75.75 0 0 1 3.75 2h5.5a.75.75 0 0 1 .53.22l3 3a.75.75 0 0 1 .22.53v7.5A1.75 1.75 0 0 1 11.25 15H4.75A1.75 1.75 0 0 1 3 13.25Zm1 .75v9.75c0 .138.112.25.25.25h6.5c.138 0 .25-.112.25-.25V6.5H9.5a1 1 0 0 1-1-1V3.5H4.25a.25.25 0 0 0-.25.25Zm6 .25V5.5h1.5Z',
            graph: 'M1.75 2.5a.75.75 0 0 0 0 1.5h.443l2.168 5.42a.75.75 0 0 0 1.388 0l1.07-2.675 1.094 3.283a.75.75 0 0 0 1.4.12L12.1 5h2.15a.75.75 0 0 0 0-1.5h-2.6a.75.75 0 0 0-.659.393L9.5 7.4 8.37 4.06a.75.75 0 0 0-1.4-.06L5.7 6.953 3.93 2.9A.75.75 0 0 0 3.2 2.5Z',

            // status icons
            'check-circle': 'M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14Zm3.78-8.72a.75.75 0 0 1 0 1.06l-4 4a.75.75 0 0 1-1.06 0l-2-2a.75.75 0 1 1 1.06-1.06L7 9.94l3.22-3.22a.75.75 0 0 1 1.06 0Z',
            alert: 'M7.53 1.21a1 1 0 0 1 1.94 0l6.17 11.94A1 1 0 0 1 14.76 15H1.24a1 1 0 0 1-.88-1.85L7.53 1.21zM8 5a.75.75 0 0 0-.75.82l.25 3a.5.5 0 0 0 1 0l.25-3A.75.75 0 0 0 8 5zm0 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z',
            'circle-slash': 'M8 1.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13Zm3.182 2.318a5 5 0 0 1 .768 6.14L4.042 2.05A5 5 0 0 1 11.182 3.818ZM2.05 4.042l7.296 7.296A5 5 0 0 1 2.05 4.042Z'
        };
        const d = pathMap[name] || pathMap.file;
        return `<svg aria-hidden="true" height="16" viewBox="0 0 16 16" width="16" style="vertical-align: text-bottom; fill: currentColor;"><path d="${d}"></path></svg>`;
    };

    S.ensureBtn = function ensureBtn(parent, id, labelHtml, onClick, extraClass = '') {
        if (!parent) return null;
        let btn = parent.querySelector(`#${id}`);
        if (btn) return btn;
        btn = document.createElement('button');
        btn.id = id;
        btn.type = 'button';
        btn.className = `btn btn-sm striffs-local-btn ${extraClass}`.trim();
        btn.style.margin = '0';
        btn.innerHTML = labelHtml;
        btn.addEventListener('click', (e) => { e.preventDefault(); onClick?.(e); });
        parent.appendChild(btn);
        return btn;
    };

    S.revealToolbarButtons = () => {
        const slot = document.getElementById('striffs-toolbar-slot');
        if (slot) slot.style.visibility = 'visible';
    };

    // Simple mount: add 2 buttons in the main toolbar, before "x/x viewed"
    S.mountMainBarButtons = function mountMainBarButtons() {
        const toolbar = S.getMainToolbar();
        if (!toolbar) return;

        const row = S.getToolbarControlsRow(toolbar) || toolbar;

        let slot = document.getElementById('striffs-toolbar-slot');
        if (slot && slot.parentElement !== row) {
            slot.parentElement.removeChild(slot);
            slot = null;
        }

        if (!slot) {
            slot = document.createElement('span');
            slot.id = 'striffs-toolbar-slot';
            slot.style.display = 'inline-flex';
            slot.style.gap = '6px';
            slot.style.alignItems = 'center';
            slot.style.marginLeft = '8px';
            slot.style.visibility = 'hidden';

            const viewedCount = row.querySelector(
                'span[class*="ViewedFileProgress-module__FilesCountText"]'
            );
            if (viewedCount) {
                const viewedContainer = viewedCount.closest('div') || viewedCount;
                if (viewedContainer && viewedContainer.parentElement) {
                    viewedContainer.parentElement.insertBefore(slot, viewedContainer);
                } else {
                    row.appendChild(slot);
                }
            } else {
                row.appendChild(slot);
            }
        }

        const onDiffClick = () => {
            S.showDiffView();
            S.saveActiveTab('diffs');
        };

        const onStriffClick = async () => {
            // FIRST PHASE: diagram not ready yet → generate only, stay on diffs.
            if (!S.__striffsReady || !S.__striffsSvg || !S.__striffsPanzoom) {
                S.updateStriffButton({
                    loading: true,
                    tooltip: "Generating Striffs…",
                    phase: "Analyzing files..."
                });

                const ok = await S.autoFetchStriffs();
                // autoFetchStriffs sets button to success/neutral/error and
                // updates __striffsReady / __striffsSvg.
                if (!ok) return;

                // Do NOT change view here. User stays on diffs.
                return;
            }

            // SECOND PHASE: diagram ready → always show Striffs view.
            S.showStriffView();
            S.saveActiveTab('striffs');
        };

        S.ensureBtn(
            slot,
            'diffs-btn',
            `${S.octicon('file')}<span class="striffs-local-btn-label"> Diffs</span>`,
            onDiffClick
        );
        S.ensureBtn(
            slot,
            'striffs-btn',
            `${S.octicon('graph')}<span class="striffs-local-btn-label"> Striffs</span>`,
            onStriffClick
        );

        S.restoreStriffButtonState?.();
        S.setActiveButtons?.(S.getCurrentView());
    };

    S.restoreStriffButtonState = () => {
        if (!S.__lastStriffsButtonState) return;
        S.updateStriffButton({ ...S.__lastStriffsButtonState });
    };

    // Button state / label updater
    S.updateStriffButton = function updateStriffButton({
        loading = false,
        success = false,
        failure = false,
        disabled = false,
        neutral = false,
        tooltip = "",
        phase = ""
    }) {
        S.__lastStriffsButtonState = {
            loading,
            success,
            failure,
            disabled,
            neutral,
            tooltip,
            phase
        };

        const btn = document.querySelector("#striffs-btn");
        if (!btn) return;

        btn.classList.remove('is-error');

        const isDisabled = disabled || loading || failure || neutral;
        btn.disabled = isDisabled;
        btn.title = tooltip || "";

        const iconWrap = (svg, colorVar) =>
            `<span class="striffs-status" style="display:inline-flex;align-items:center;justify-content:center;color: var(${colorVar});">${svg}</span>`;

        if (loading) {
            const phaseText = phase ? ` ${phase}` : " Loading...";
            btn.innerHTML =
                `<span class="loader" style="display:inline-block;width:16px;height:16px;border:2px solid var(--borderColor-muted, var(--color-border-default, #ccc));border-top:2px solid var(--accent-fg, #0969da);border-radius:50%;animation:spin .8s linear infinite;vertical-align:middle;margin-right:8px;"></span>${phaseText}`;
            return;
        }

        if (failure) {
            btn.classList.add('is-error');
            const icon = iconWrap(S.octicon('alert'), '--color-danger-fg, #d1242f');
            btn.innerHTML = `${icon}<span class="striffs-local-btn-label">Striffs</span>`;
            return;
        }

        if (neutral) {
            const icon = iconWrap(S.octicon('circle-slash'), '--fgColor-muted, #6e7781');
            btn.innerHTML = `${icon}<span class="striffs-local-btn-label">Striffs</span>`;
            return;
        }

        if (success) {
            const icon = iconWrap(S.octicon('check-circle'), '--success-fg, var(--color-success-fg, #1a7f37)');
            btn.innerHTML = `${icon}<span class="striffs-local-btn-label">Striffs</span>`;
            return;
        }

        if (disabled) {
            const icon = iconWrap(S.octicon('circle-slash'), '--fgColor-muted, #6e7781');
            btn.innerHTML = `${icon}<span class="striffs-local-btn-label">Striffs</span>`;
            return;
        }

        btn.innerHTML = `${S.octicon('graph')}<span class="striffs-local-btn-label"> Striffs</span>`;
    };

    // --- Global toast helpers (theme-aware) ---
    S.ensureGlobalToast = function ensureGlobalToast() {
        let t = document.getElementById('striffs-global-toast');
        if (t) return t;
        t = document.createElement('div');
        t.id = 'striffs-global-toast';
        t.setAttribute('aria-live', 'polite');
        t.setAttribute('role', 'status');
        t.style.pointerEvents = 'none';
        document.body.appendChild(t);
        return t;
    };

    S.toast = function toast(message, type = 'info', { timeoutMs = 7500 } = {}) {
        S.ensureGlobalToast();

        const el = document.createElement('div');
        el.className = `striffs-toast-item striffs-toast-${type}`;
        el.innerHTML = `
    <span class="striffs-toast-dot" aria-hidden="true"></span>
    <div class="striffs-toast-msg">${message}</div>
  `;

        const host = document.getElementById('striffs-global-toast');
        host.appendChild(el);

        requestAnimationFrame(() => el.classList.add('show'));

        const remove = () => {
            el.classList.remove('show');
            setTimeout(() => el.remove(), 240);
        };
        const t = setTimeout(remove, Math.max(7500, timeoutMs));
        el.addEventListener('click', () => { clearTimeout(t); remove(); }, { passive: true });
    };

    // Compute and set #striff-diagram-view height (~80% viewport)
    S.resizeStriffView = function resizeStriffView() {
        const el = document.getElementById('striff-diagram-view');
        if (!el) return;
        el.style.height = '80vh';
    };

    S.addSpinAnimation = function addSpinAnimation() {
        if (S.__styleInjected) return;
        const style = document.createElement("style");
        style.id = "striffs-style";
        style.textContent = `
  @keyframes spin{from{transform:rotate(0)}to{transform:rotate(360deg)}}

  .striffs-local-btn {
    color: var(--fgColor-default, var(--color-fg-default, #24292f));
    background: var(--button-default-bgColor-rest, var(--color-btn-bg, #f6f8fa));
    border: 1px solid var(--borderColor-muted, var(--color-border-default, #d0d7de));
    line-height: 20px;
    display: inline-flex;
    align-items: center;
    gap: 3px;
    padding: 2px 12px;
    border-radius: 6px;
    transition: background-color .12s ease, border-color .12s ease, color .12s ease;
  }
  .striffs-local-btn:hover {
    background: var(--button-default-bgColor-hover, var(--color-btn-hover-bg, #eef1f4));
    text-decoration: none;
  }
  .striffs-local-btn:disabled {
    opacity: .75;
    cursor: not-allowed;
    filter: grayscale(0.2);
  }

  #striffs-global-toast {
    position: fixed;
    top: 14px;
    right: 14px;
    z-index: 999999;
    display: flex;
    flex-direction: column;
    gap: 10px;
  }

  .striffs-toast-item {
    pointer-events: auto;
    display: flex;
    align-items: center;
    gap: 10px;
    max-width: min(640px, 92vw);
    padding: 12px 14px;
    border-radius: 10px;
    box-shadow: 0 4px 16px rgba(0,0,0,.22);
    border: 1px solid var(--borderColor-muted, var(--color-border-default, #d0d7de));
    background: var(--bgColor-default, var(--color-canvas-default, #fff));
    color: var(--fgColor-default, var(--color-fg-default, #24292f));
    transform: translateY(-8px);
    opacity: 0;
    transition: opacity .2s ease, transform .2s ease, background-color .18s ease, border-color .18s ease;
    font-size: 14px;
    font-weight: 500;
  }
  .striffs-toast-item.show {
    transform: translateY(0);
    opacity: 1;
  }

  .striffs-toast-dot {
    width: 10px; height: 10px; border-radius: 50%;
    flex: 0 0 10px;
  }
  .striffs-toast-info     { border-color: var(--accent-fg, var(--color-accent-fg, #0969da)); }
  .striffs-toast-info .striffs-toast-dot { background: var(--accent-fg, var(--color-accent-fg, #0969da)); }

  .striffs-toast-success  { border-color: var(--success-fg, var(--color-success-fg, #1a7f37)); }
  .striffs-toast-success .striffs-toast-dot { background: var(--success-fg, var(--color-success-fg, #1a7f37)); }

  .striffs-toast-error    { border-color: var(--borderColor-danger, var(--color-danger-fg, #d1242f)); }
  .striffs-toast-error .striffs-toast-dot { background: var(--borderColor-danger, var(--color-danger-fg, #d1242f)); }

  .striffs-toast-neutral  { border-color: var(--borderColor-muted, var(--color-border-default, #8b949e)); }
  .striffs-toast-neutral .striffs-toast-dot { background: var(--borderColor-muted, var(--color-border-default, #8b949e)); }

  .striffs-local-btn.is-active {
    color: var(--accent-fg, var(--color-accent-fg, #0969da));
    border-color: var(--accent-fg, var(--color-accent-fg, #0969da));
    background: color-mix(in srgb, var(--accent-fg, #0969da) 12%, transparent);
  }

  .striffs-local-btn.is-error {
    color: var(--fgColor-default, var(--color-fg-default, #24292f));
    border-color: var(--borderColor-danger, var(--color-danger-fg, #d1242f));
    background: color-mix(in srgb, var(--borderColor-danger, #d1242f) 12%, transparent);
  }

  #striff-diagram-view{
    min-height: 50vh;
    overflow: hidden;
    position: relative;
    width: 100%;
    border: 1px solid #444;
  }
  #striff-diagram-view .striff-svg-wrap{
    position: relative;
    width: 100%;
    height: 100%;
  }
  #striff-diagram-view svg{
    width: 100%;
    height: 100%;
    display: block;
    cursor: move;
  }
  #striffs-toast{position:absolute;top:6px;left:8px;background:var(--bgColor-default, #fff);border:1px solid #f0a3a3;color:#b00020;padding:6px 10px;border-radius:6px;font-size:12px;box-shadow:0 1px 4px rgba(0,0,0,.08);opacity:0;transition:opacity .2s}
  #striffs-toast.show{opacity:1}
  `;
        document.head.appendChild(style);
        S.__styleInjected = true;
    };

    S.setActiveButtons = function setActiveButtons(which /* 'diffs' | 'striffs' */) {
        const diffs = document.querySelector('#diffs-btn');
        const striffs = document.querySelector('#striffs-btn');
        diffs?.classList.remove('is-active');
        striffs?.classList.remove('is-active');

        const id = which === 'diffs' ? '#diffs-btn' : '#striffs-btn';
        const btn = document.querySelector(id);
        if (btn) btn.classList.add('is-active');
    };

    // ---------- Containers / Show-Hide ----------

    function getNewUIDiffWrapper() {
        const diff = document.querySelector('div[class*="Diff-module__diff"]');
        if (!diff) return null;

        let parent = diff.parentElement;
        while (parent && parent !== document.body) {
            if (parent.querySelector(':scope > div[class*="Diff-module__diff"]')) {
                return parent;
            }
            parent = parent.parentElement;
        }
        return diff.parentElement;
    }

    S.getFilesWrapper = () =>
        getNewUIDiffWrapper() ||
        S.$$first([
            '#files',
            'div[data-testid="files-changed"]',
            'div[data-view-component="true"][data-testid="pull-requests-files"]',
            'main[aria-label="Content"] #files',
            '#pr-file-tree',
        ]);

    S.ensureStriffContainer = () => {
        let striffView = document.getElementById("striff-diagram-view");
        if (!striffView) {
            const filesWrapper = S.getFilesWrapper();
            if (!filesWrapper) return null;
            striffView = document.createElement("div");
            striffView.id = "striff-diagram-view";
            striffView.style.marginTop = "20px";
            striffView.style.display = "none";
            striffView.innerHTML = `<div id="striffs-toast" role="status" aria-live="polite"></div><p>Loading Striffs...</p>`;
            filesWrapper.appendChild(striffView);
        } else if (!striffView.querySelector("#striffs-toast")) {
            striffView.insertAdjacentHTML("afterbegin", `<div id="striffs-toast" role="status" aria-live="polite"></div>`);
        }
        return striffView;
    };

    const DIFF_CONTAINERS_SELECTORS = [
        '[data-testid="file-diff-split"]',
        '[data-testid="file-diff-unified"]',
        'div[class*="Diff-module__diff"]',
        '.js-diff-progressive-container',
        'div.js-file[data-file-type="file"]'
    ];
    const NEW_UI_DIFF_SELECTOR = 'div[class*="Diff-module__diff"], .js-diff-progressive-container, div.js-file[data-file-type="file"]';

    S.hideAllDiffs = () => {
        const newDiffs = Array.from(document.querySelectorAll(NEW_UI_DIFF_SELECTOR));
        newDiffs.forEach(el => {
            if (!el.dataset.striffsDisplay) {
                el.dataset.striffsDisplay = el.style.display || '';
            }
            el.style.display = 'none';
        });

        S.$$all(DIFF_CONTAINERS_SELECTORS).forEach(el => {
            if (!el.dataset.striffsDisplay) {
                el.dataset.striffsDisplay = el.style.display || '';
            }
            el.style.display = "none";
        });
    };

    S.showAllDiffs = () => {
        const selectors = [
            NEW_UI_DIFF_SELECTOR,
            ...DIFF_CONTAINERS_SELECTORS,
            '#files',
            'div[data-testid="files-changed"]',
            'div[data-view-component="true"][data-testid="pull-requests-files"]'
        ];
        selectors.forEach(sel => {
            document.querySelectorAll(sel).forEach(el => {
                if (el.dataset && 'striffsDisplay' in el.dataset) {
                    const prev = el.dataset.striffsDisplay;
                    el.style.display = prev !== undefined ? prev : '';
                    delete el.dataset.striffsDisplay;
                } else {
                    el.style.display = '';
                }
            });
        });
    };

    S.showDiffView = () => {
        S.capturePanState?.();
        S.persistPanState?.();
        S.showAllDiffs();
        const striffView = document.getElementById("striff-diagram-view");
        if (striffView) striffView.style.display = "none";
        S.setCurrentView('diffs');
    };

    S.showStriffView = () => {
        S.hideAllDiffs();
        const striffView = S.ensureStriffContainer();
        if (striffView) {
            striffView.style.display = "block";
            S.resizeStriffView();
            if (S.__striffsSvg && S.__striffsPanzoom) {
                const restored = S.restorePanState?.();
                const fitDone = State?.isInitialFitDone?.();
                if (!restored && !fitDone) {
                    S.fitSvgToContainer(S.__striffsSvg, S.__striffsPanzoom);
                    S.capturePanState?.();
                    State?.markInitialFitDone?.();
                }
            }
        }
        S.setCurrentView('striffs');
    };

    S.saveActiveTab = (tabName) => {
        try { chrome.storage.local.set({ striffsActiveTab: tabName }); } catch (e) { cwarn('saveActiveTab failed', e); }
    };

    S.getSavedActiveTab = async () =>
        new Promise((resolve) => {
            try {
                chrome.storage.local.get(["striffsActiveTab"], (result) => resolve(result?.striffsActiveTab || "diffs"));
            } catch {
                resolve("diffs");
            }
        });

    // Persist pan state on tab close/visibility changes to survive PJAX/Turbo swaps
    const persistOnHidden = () => {
        if (document.visibilityState === 'hidden') {
            S.persistPanState?.();
        }
    };
    document.addEventListener('visibilitychange', persistOnHidden, { passive: true });
    window.addEventListener('beforeunload', () => S.persistPanState?.());

    S.ensureToolbarObserver?.();
    S.ensureFilesObserver?.();
})();


// ---- src/striffs-pr.js ----
// Striffs — PR helpers & mapping
(() => {
  const S = (window.Striffs = window.Striffs || {});
  const { cwarn } = S;

  const getCachedUpdatedAtFor = (owner, repo, pull_number) => {
    if (!owner || !repo || !pull_number) return null;
    try {
      const key = `striffs:${owner}/${repo}#${pull_number}`;
      const raw = localStorage.getItem(key);
      if (!raw) return null;
      const parsed = JSON.parse(raw);
      return parsed?.updated_at || null;
    } catch (e) {
      cwarn?.('readCachedUpdatedAt failed', e);
      return null;
    }
  };

  const getUpdatedAtFromMeta = () => {
    const selectors = [
      'meta[name="octolytics-dimension-pull_request_updated_at"]',
      'meta[name="octolytics-dimension-issue_updated_at"]',
      'meta[property="og:updated_time"]'
    ];
    for (const sel of selectors) {
      const val = document.querySelector(sel)?.getAttribute('content');
      if (val) return val;
    }
    return null;
  };

  const getUpdatedAtFromEmbeddedData = () => {
    const scripts = document.querySelectorAll('script[data-target="react-app.embeddedData"]');
    for (const script of scripts) {
      const text = script?.textContent || script?.innerText || '';
      if (!text) continue;
      try {
        const json = JSON.parse(text);
        const payload = json?.payload || json?.data || json;
        const val = payload?.pullRequest?.updatedAt ||
                    payload?.pullRequest?.updated_at ||
                    payload?.issue?.updatedAt ||
                    payload?.issue?.updated_at;
        if (val) return val;
      } catch (e) {
        // ignore malformed blocks
      }
    }
    return null;
  };

  const getUpdatedAtFromDom = () =>
    document.querySelector('relative-time')?.getAttribute('datetime') ||
    document.querySelector('time-ago')?.getAttribute('datetime') ||
    document.querySelector('time')?.getAttribute('datetime') ||
    null;

  const resolveUpdatedAt = (owner, repo, pull_number) =>
    getUpdatedAtFromMeta() ||
    getUpdatedAtFromEmbeddedData() ||
    getUpdatedAtFromDom() ||
    S.__lastFetchedUpdatedAt ||
    getCachedUpdatedAtFor(owner, repo, pull_number) ||
    new Date().toISOString();

  // ---------- PR metadata ----------
  S.extractPRMetadata = () => {
    const [, owner, repo, , pull_number] = window.location.pathname.split("/");
    const updated_at = resolveUpdatedAt(owner, repo, pull_number);
    return { owner, repo, pull_number, updated_at };
  };

  // ---------- File path helpers ----------
  S.stripRenamePath = (txt) => {
    if (!txt) return txt;
    const parts = String(txt).split(/→|->/);
    if (parts.length > 1) {
      return parts[parts.length - 1].trim();
    }
    return txt;
  };

  // ---------- Files in PR ----------
  S.getFilesInPR = () => {
    const els = S.$$all([
      ".file-info a.Link--primary",
      '[data-testid="file-header"] a.Link--primary',
      'a[data-testid="file-name"], a[data-hovercard-type="file"]'
    ]);
    const titles = els
      .map(el => el.getAttribute("title") || el.textContent || "")
      .map(t => S.stripRenamePath(t).trim())
      .filter(Boolean);
    return titles.map(t => t.toLowerCase());
  };

  S.checkIfRelevantFilesExist = (filenames, supportedExts) =>
    filenames.some(filename => {
      const parts = filename.toLowerCase().split(".");
      const ext = parts.length > 1 ? parts.pop() : "";
      return supportedExts.includes(ext);
    });

  // ---------- Mapping ----------
  S.normalizePath = (p) => String(p || "").replace(/\\/g, "/").replace(/^\/+/, "").trim();
  S.cssEscape = (id) => String(id).replace(/(["\\\]])/g, "\\$1");

  S.buildPathIdMapping = (apiData) => {
    S.__striffsPathToComponentId.clear();
    S.__striffsComponentIdToFile.clear();
    if (!S.__striffsSvg) return;

    const existsInSvg = (id) =>
      !!id && (S.__striffsSvg.querySelector(`[id="${S.cssEscape(id)}"]`) ||
        (typeof S.__striffsSvg.getElementById === "function" && S.__striffsSvg.getElementById(id)));

    const items = Array.isArray(apiData?.striffs) ? apiData.striffs : [];
    const parsedFiles = [];
    const missingInSvg = [];
    const componentsDump = [];

    for (const item of items) {
      let comps = [];
      try {
        if (item.diagramCmpsJSON) comps = JSON.parse(item.diagramCmpsJSON);
      } catch (e) { /* ignore */ }
      for (const comp of comps) {
        const file = comp.sourceFile;
        const id = comp.uniqueName;
        if (!file || !id) continue;
        const norm = S.normalizePath(file);
        componentsDump.push({ id, file: "/" + norm, inSvg: existsInSvg(id) });
        parsedFiles.push(norm);
        if (existsInSvg(id)) {
          S.__striffsPathToComponentId.set("/" + norm, id);
          S.__striffsPathToComponentId.set(norm, id);
          S.__striffsComponentIdToFile.set(id, "/" + norm);
        } else {
          missingInSvg.push({ id, file: norm });
        }
      }
    }

    try {
      const sample = Array.from(S.__striffsPathToComponentId.entries()).slice(0, 10);
      const uniqueFiles = Array.from(new Set(parsedFiles));
      S.cinfo('Striffs path/component map', {
        mappedPaths: S.__striffsPathToComponentId.size,
        mappedComponents: S.__striffsComponentIdToFile.size,
        filesFromApi: uniqueFiles.length,
        sample
      });
      if (missingInSvg.length) {
        S.cwarn('Striffs components missing in SVG (sample)', missingInSvg.slice(0, 10));
      }
    } catch (e) {
      S.cwarn?.('Striffs map logging failed', e);
    }
  };

  S.findSvgTextForFile = (fullPath) => {
    if (!S.__striffsSvg) return null;
    const norm = S.normalizePath(fullPath);
    const mappedId = S.__striffsPathToComponentId.get("/" + norm) || S.__striffsPathToComponentId.get(norm);
    if (!mappedId) return null;
    return S.__striffsSvg.querySelector(`text[id="${S.cssEscape(mappedId)}"]`);
  };

  const ensureLeadingSlash = (p) => p.startsWith('/') ? p : `/${p}`;
  const isPathLike = (p) => {
    if (!p) return false;
    if (/^file-tree-item-diff-/i.test(p)) return false;
    if (/^[a-f0-9]{32,}$/i.test(p)) return false; // pure hash
    const parts = p.split('/').filter(Boolean);
    if (parts.length <= 1) return false; // drop bare filenames/ids
    return true;
  };
  const isDirectoryNode = (node) => {
    const li = node?.closest?.('li');
    if (!li) return false;
    const type = li.getAttribute('data-tree-entry-type');
    if (type && type.toLowerCase() === 'directory') return true;
    if (li.querySelector?.('svg[class*="file-directory"]')) return true;
    return false;
  };

  S.getFilterFilesFromNav = () => {
    const paths = new Set();
    const strip = (txt) => S.stripRenamePath(txt || "");

    // File tree entries (modern)
    const treeItems = S.$$all([
      "[data-testid='file-tree'] li [data-testid='file-tree-item-text']",
      "[data-testid='file-tree'] li a.ActionListContent",
    ]);
    treeItems.forEach(span => {
      if (isDirectoryNode(span)) return;
      const txt = strip(span?.textContent)?.trim();
      if (!txt) return;
      const norm = S.normalizePath(txt);
      if (isPathLike(norm)) paths.add(ensureLeadingSlash(norm));
    });

    // Diff headers (works even if the tree isn't rendered yet)
    const headerLinks = S.$$all([
      "[data-testid='file-header'] a.Link--primary",
      "a[data-testid='file-name']",
      "a[data-hovercard-type='file']"
    ]);
    headerLinks.forEach(el => {
      const txt = strip(el.getAttribute("title") || el.textContent || "").trim();
      if (!txt) return;
      const norm = S.normalizePath(txt);
      if (isPathLike(norm)) paths.add(ensureLeadingSlash(norm));
    });

    // Already-built map of file->diff ids (if present)
    if (S.__filePathToDiffId && typeof S.__filePathToDiffId.keys === 'function') {
      for (const key of S.__filePathToDiffId.keys()) {
        const norm = S.normalizePath(key);
        if (isPathLike(norm)) paths.add(ensureLeadingSlash(norm));
      }
    }

    return Array.from(paths);
  };

  S.buildFilePathToDiffIdMapAsync = () => {
    Promise.resolve().then(() => {
      const map = new Map();
      const items = S.$$all([
        "[data-testid='file-tree'] li",
      ]);
      for (const li of items) {
        const span = li.querySelector("[data-testid='file-tree-item-text']");
        const a = li.querySelector("a.ActionListContent, a[href^='#diff-'], a[href*='#diff-']");
        const href = a?.getAttribute("href") || "";
        const diffId = (href.startsWith("#") ? href.slice(1) : (href.match(/#(.+)$/)?.[1] || null));
        if (!span || !diffId) continue;
        const fullPath = "/" + S.normalizePath(S.stripRenamePath(span.textContent.trim()));
        map.set(fullPath, diffId);
        map.set(S.normalizePath(S.stripRenamePath(span.textContent.trim())), diffId);
      }
      S.__filePathToDiffId = map;
    });
  };

  // --- PR refs parsing (robust) ---
  S.extractHeadBaseRefs = () => {
    let anchors = Array.from(document.querySelectorAll(".commit-ref > a"));
    if (anchors.length < 2) {
      anchors = Array.from(document.querySelectorAll('a[data-hovercard-type="repository"].Link--primary, a[data-hovercard-type="repository"].Link--muted'));
    }
    if (anchors.length < 2) {
      anchors = Array.from(document.querySelectorAll('a[href*="/tree/"]'));
    }

    const parseRef = (anchor) => {
      if (!anchor) return { owner: "", repo: "", branch: "" };
      const href = anchor.getAttribute("href") || "";
      const parts = href.split("/").filter(Boolean);
      const owner = parts[0] || "";
      const repo = parts[1] || "";
      const branch = decodeURIComponent(parts.slice(3).join("/")) || "";
      return { owner, repo, branch };
    };

    const base = parseRef(anchors[0]), head = parseRef(anchors[1]);
    return { baseOwner: base.owner, baseRepo: base.repo, baseBranch: base.branch, headOwner: head.owner, headRepo: head.repo, headBranch: head.branch };
  };
})();


// ---- src/striffs-render-cache.js ----
// Striffs — rendering & cache
(() => {
    const S = (window.Striffs = window.Striffs || {});
    const { cwarn, cerr } = S;

    // ---------- Validation ----------
    S.isValidStriffsResult = (result) => {
        if (!result || typeof result !== "object") return false;
        if (result.error || result.message === "error") return false;
        if (!Array.isArray(result.striffs)) return false;
        return true;
    };

    // Ensure we have cssEscape on S (used by previous logic)
    S.cssEscape = S.cssEscape || function cssEscape(id) {
        return String(id).replace(/(["\\\]])/g, "\\$1");
    };

    // Hover / click styling: color only text nodes that correspond to files
    // so they look like links (blue) and feel clickable.
    S.applyHoverability = function applyHoverability() {
        if (!S.__striffsSvg || !S.__striffsComponentIdToFile) return;

        try {
            for (const id of S.__striffsComponentIdToFile.keys()) {
                const esc =
                    (window.CSS && typeof CSS.escape === "function")
                        ? CSS.escape(id)
                        : S.cssEscape(id);

                let textEl =
                    S.__striffsSvg.querySelector(`text[id="${esc}"]`) ||
                    S.__striffsSvg.getElementById(id);
                if (!textEl) continue;

                const existingStyle = textEl.getAttribute("style") || "";
                const parts = existingStyle
                    .split(";")
                    .map(s => s.trim())
                    .filter(s => s && !s.toLowerCase().startsWith("fill:") && !s.toLowerCase().startsWith("cursor:"));

                // GitHub-ish link blue; use accent vars with a hex fallback.
                parts.push(
                    "fill: var(--fgColor-accent, var(--color-accent-fg, #0969da))",
                    "cursor: pointer"
                );

                textEl.setAttribute("style", parts.join("; "));
            }
        } catch (e) {
            cwarn("applyHoverability failed", e);
        }
    };

    // ---------- Cache ----------
    S.cacheKey = () => {
        const { owner, repo, pull_number } = S.extractPRMetadata();
        return `striffs:${owner}/${repo}#${pull_number}`;
    };

    S.primeDiagramFromCache = () => {
        try {
            S.__lastLoadSource = 'none';
            const key = S.cacheKey();
            const raw = localStorage.getItem(key);
            if (!raw) return;
            const parsed = JSON.parse(raw);
            const { updated_at } = S.extractPRMetadata();
            const freshUpdatedAt = parsed.updated_at === updated_at;
            const freshTime = (Date.now() - (parsed.savedAt || 0)) < S.CACHE_TTL_MS;
            if (freshUpdatedAt && freshTime && parsed.result && Array.isArray(parsed.result.striffs)) {
                const container = S.ensureStriffContainer();
                if (container) {
                    const rendered = S.renderStriffsInto(container, parsed.result);
                    if (rendered) {
                        S.__lastLoadSource = 'cache';
                        S.__striffsReady = true;
                        S.__lastFetchedUpdatedAt = updated_at;
                        S.updateStriffButton({ success: true, tooltip: "Striffs loaded from cache. Click to view." });
                    }
                }
            }
        } catch (e) {
            cwarn('primeDiagramFromCache failed', e);
        }
    };

    S.storeDiagramInCache = (result) => {
        try {
            const key = S.cacheKey();
            const { updated_at } = S.extractPRMetadata();
            const payload = { updated_at, savedAt: Date.now(), result };
            localStorage.setItem(key, JSON.stringify(payload));
        } catch (e) {
            cwarn('storeDiagramInCache failed (quota?)', e);
        }
    };

    // ---------- SVG dimension sanitizer ----------
    // Only enforce width/height to 100% so the SVG fills the container;
    // do not touch viewBox or other styling.
    S.sanitizeSvgDimensions = function sanitizeSvgDimensions(svg) {
        try {
            if (!svg) return;

            svg.setAttribute('width', '100%');
            svg.setAttribute('height', '100%');
            svg.setAttribute('preserveAspectRatio', 'xMidYMid meet');

            const style = svg.getAttribute('style');
            if (style) {
                const cleaned = style
                    .split(';')
                    .map(s => s.trim())
                    .filter(s => s && !s.toLowerCase().startsWith('width:') && !s.toLowerCase().startsWith('height:'))
                    .join('; ');
                if (cleaned) {
                    svg.setAttribute('style', cleaned);
                } else {
                    svg.removeAttribute('style');
                }
            }
        } catch (e) {
            S.cwarn('sanitizeSvgDimensions failed', e);
        }
    };

    // ---------- Rendering ----------
    const b64ToBytes = (b64) => Uint8Array.from(atob(b64), c => c.charCodeAt(0));

    S.renderStriffsInto = (target, data) => {
        if (!target) return false;
        const State = S.state;
        State?.resetTooLarge?.();
        target.innerHTML = `<div id="striffs-toast" role="status" aria-live="polite"></div><div id="striffs-status">Rendering diagram…</div>`;

        const items = Array.isArray(data?.striffs) ? data.striffs : [];

        if (items.length === 0) {
            target.innerHTML = `<div id="striffs-toast" role="status" aria-live="polite"></div>`;
            S.updateStriffButton({ neutral: true, disabled: true, tooltip: "No changes were found" });
            S.toast?.("No changes were found.", "neutral", { timeoutMs: 5000 });
            return true;
        }

        let renderableFound = false;

        for (const item of items) {
            try {
                let svgText = "";
                if (item.svgCode) {
                    svgText = item.svgCode;
                } else if (item.base64encodedSVGCode) {
                    svgText = atob(item.base64encodedSVGCode);
                } else if (item.gzippedBase64Svg) {
                    const raw = b64ToBytes(item.gzippedBase64Svg);
                    if (!window.fflate) throw new Error("fflate not loaded");
                    const u8 = window.fflate.gunzipSync(raw);
                    svgText = new TextDecoder("utf-8").decode(u8);
                } else {
                    continue; // no renderable payload in this item
                }
                renderableFound = true;
                target.innerHTML = `<div id="striffs-toast" role="status" aria-live="polite"></div><div id="striffs-status">Rendering diagram…</div>`;
                const wrap = document.createElement("div");
                wrap.className = "striff-svg-wrap";
                wrap.innerHTML = svgText;
                target.appendChild(wrap);

                const svg = wrap.querySelector("svg");
                if (svg) {
                    S.sanitizeSvgDimensions(svg);
                }

                if (svg && window.panzoom) {
                    State?.resetPanState?.();
                    State?.resetInitialFit?.();
                    // Pan/zoom on the SVG root so fit math matches the viewBox; preserveAspectRatio keeps text from squishing.
                    const node = svg;
                    S.__striffsPanzoom = window.panzoom(node, { contain: "inside", maxScale: 3, minScale: 0.5 });
                    if (typeof S.__striffsPanzoom.on === 'function') {
                        try {
                            S.__striffsPanzoom.on('transform', () => S.capturePanState?.());
                        } catch (e) {
                            cwarn('panzoom transform listener failed', e);
                        }
                    }
                    S.__striffsSvg = svg;
                    const restored = S.restorePanState?.();
                    if (!restored) {
                        S.fitSvgToContainer(svg, S.__striffsPanzoom);
                        S.capturePanState?.();
                        State?.markInitialFitDone?.();
                    } else {
                        State?.markInitialFitDone?.();
                    }
                    S.buildPathIdMapping(data);
                    S.applyHoverability(); // now colors clickable text
                }

                const s = document.getElementById("striffs-status");
                if (s) s.textContent = "Diagram ready.";
                setTimeout(() => s?.remove(), 800);
                return true;
            } catch (e) {
                cerr("Failed to decode/render SVG", e);
            }
        }

        if (!renderableFound && items.length > 0) {
            target.innerHTML = `<div id="striffs-toast" role="status" aria-live="polite"></div><div style="color:#d1242f;">❗ Diagram too large to render. No SVG was generated.</div>`;
            S.__striffsReady = false;
            State?.setTooLarge?.(true);
            S.updateStriffButton?.({ neutral: true, disabled: true, tooltip: "Diagram too large to render" });
            S.toast?.("Diagram too large to render. No SVG was generated.", "neutral", { timeoutMs: 5000 });
            return true; // handled gracefully
        }

        target.innerHTML = `<div id="striffs-toast" role="status" aria-live="polite"></div><div style="color:#d1242f;">❌ Failed to render Striffs diagram.</div>`;
        return false;
    };

    S.fitSvgToContainer = (svg, pan) => {
        try {
            const striffView = document.getElementById("striff-diagram-view") || svg.parentElement;
            if (typeof S.resizeStriffView === 'function') S.resizeStriffView();
            const rect = striffView.getBoundingClientRect();
            const width  = rect.width  || striffView.clientWidth  || window.innerWidth  || 1200;
            const height = rect.height || striffView.clientHeight || window.innerHeight || 800;

            const root = svg.querySelector("g") || svg;
            const viewBox = svg.getAttribute('viewBox');
            let box = null;
            if (viewBox) {
                const parts = viewBox.split(/\s+/).map(Number).filter(n => Number.isFinite(n));
                if (parts.length === 4) {
                    const [x, y, w, h] = parts;
                    box = { x, y, width: w, height: h };
                }
            }
            if (!box) {
                const bbox = root.getBBox();
                box = { x: bbox.x, y: bbox.y, width: bbox.width, height: bbox.height };
            }

            const padFactor = 0.9; // balanced fit to avoid over-zooming
            const scale = Math.min(width / (box.width || 1), height / (box.height || 1)) * padFactor;
            pan.zoomAbs(0, 0, scale);

            // Anchor the diagram near the top-left with even padding so it stays fully visible.
            const paddingX = Math.max(0, (width  - (box.width  * scale)) / 2);
            const paddingY = Math.max(0, (height - (box.height * scale)) / 2);
            const tx = paddingX - (box.x * scale);
            const ty = paddingY - (box.y * scale);
            pan.moveTo(tx, ty);
        } catch (e) {
            cwarn('fitSvgToContainer skipped', e);
        }
    };
})();


// ---- src/striffs-events-boot.js ----
// Striffs — events & boot
(async () => {
  const S = (window.Striffs = window.Striffs || {});
  const { cwarn, cerr } = S;
  const TIMEOUTS = S.TIMEOUTS || {};
  const timeoutFor = (key, fallback) =>
    typeof TIMEOUTS[key] === "number" ? TIMEOUTS[key] : fallback;

  // ---------- Listener lifecycle helpers ----------
  S.teardownDomListeners = function teardownDomListeners() {
    if (S.__onFileTreeClick) document.removeEventListener("click", S.__onFileTreeClick);
    if (S.__onDiagramClick) document.removeEventListener("click", S.__onDiagramClick);
    if (S.__onResize) window.removeEventListener("resize", S.__onResize);
    S.__onFileTreeClick = null;
    S.__onDiagramClick = null;
    S.__onResize = null;
    S.__domListenersRegistered = false;
  };

  function registerDomListeners() {
    if (S.__domListenersRegistered) return;

    S.__onFileTreeClick = (e) => {
      const link = e.target.closest(
        "a.ActionList-content, a.ActionListContent, " +
        "[data-testid='file-tree'] a[href^='#diff-'], " +
        "[data-testid='file-tree'] a[href*='#diff-']"
      );
      if (!link) return;

      const striffView = document.getElementById("striff-diagram-view");
      const striffsVisible =
        !!(striffView && window.getComputedStyle(striffView).display !== "none");

      if (!striffsVisible || !S.__striffsSvg || !S.__striffsPanzoom) {
        return;
      }

      e.preventDefault();
      e.stopPropagation();
      if (typeof e.stopImmediatePropagation === 'function') e.stopImmediatePropagation();

      const li = link.closest("li[id^='file-tree-item-diff-'], [data-testid='file-tree'] li");
      const hiddenSpan =
        li?.querySelector("span[data-filterable-item-text], [data-testid='file-tree-item-text']");
      const fullPath = '/' + (hiddenSpan?.textContent.trim() || '');
      if (S.__striffsSvg && S.__striffsPanzoom) {
        const textEl = S.findSvgTextForFile(fullPath);
        const pane = S.ensureStriffContainer();
        if (pane) pane.scrollIntoView({ block: "center", behavior: "smooth" });
        if (textEl) {
          S.centerOnElement(S.__striffsSvg, textEl, S.__striffsPanzoom, 0.85, 0.5);
          S.flashFocus(textEl);
        } else {
          S.toast?.("No corresponding component exists in the diagram for this file.", "error", { timeoutMs: 3000 });
        }
      }
    };

    S.__onDiagramClick = (e) => {
      if (!S.__striffsSvg) return;
      const target = e.target.closest("text[id]");
      if (!target) return;
      const ownerSvg = target.ownerSVGElement || target.closest("svg");
      if (ownerSvg !== S.__striffsSvg) return;

      const id = target.getAttribute("id");
      const file = S.__striffsComponentIdToFile.get(id);
      if (file) {
        S.capturePanState?.();
        S.showDiffView();
        S.setActiveButtons("diffs");
        S.saveActiveTab("diffs");

        const diffId = S.__filePathToDiffId.get(file) || S.__filePathToDiffId.get(S.normalizePath(file));
        if (diffId) {
          if (location.hash !== `#${diffId}`) history.replaceState(null, "", `#${diffId}`);
          const diffEl = document.getElementById(diffId);
          if (diffEl) diffEl.scrollIntoView({ block: "start", behavior: "smooth" });
        } else {
          S.cwarn?.('Striffs component click: file missing in diff map', { id, file });
          S.toast?.("No corresponding file exists in this Pull Request’s changeset.", "error", { timeoutMs: 3000 });
        }
      } else {
        S.cwarn?.('Striffs component click: no file mapped for component', { id });
        S.toast?.("No corresponding file exists in this Pull Request’s changeset.", "error", { timeoutMs: 3000 });
      }
    };

    S.__onResize = () => {
      const view = document.getElementById("striff-diagram-view");
      const visible = view && window.getComputedStyle ? window.getComputedStyle(view).display !== 'none' : false;
      if (!visible) return;
      if (S.__striffsSvg && S.__striffsPanzoom) {
        S.restorePanState?.();
      }
    };

    document.addEventListener("click", S.__onFileTreeClick);
    document.addEventListener("click", S.__onDiagramClick);
    window.addEventListener("resize", S.__onResize);

    S.__domListenersRegistered = true;
  }

  // ---------- Toast (legacy view-local) ----------
  S.showToast = (msg) => {
    const view = S.ensureStriffContainer();
    if (!view) return;
    const toast = view.querySelector("#striffs-toast");
    if (!toast) return;
    toast.textContent = msg;
    toast.classList.add("show");
    setTimeout(() => toast.classList.remove("show"), 7500);
  };

  // ---------- Auto fetch (background-powered) ----------
  function readCachedDiagram(updatedAt) {
    const key = S.cacheKey();
    if (!key) return null;
    const cached = localStorage.getItem(key);
    if (!cached) return null;
    try {
      const parsed = JSON.parse(cached);
      if (parsed.updated_at !== updatedAt) return null;
      if ((Date.now() - parsed.savedAt) > (S.CACHE_TTL_MS || 0)) return null;
      return parsed.result || null;
    } catch (e) {
      S.cwarn?.("Cache parse failed", e);
      return null;
    }
  }

  function writeCachedDiagram(result, updatedAt) {
    try {
      const key = S.cacheKey();
      if (!key) return;
      localStorage.setItem(key, JSON.stringify({
        result,
        updated_at: updatedAt,
        savedAt: Date.now(),
      }));
    } catch (e) {
      S.cwarn?.("Cache write failed", e);
    }
  }

  async function requestWithToken(token, meta) {
    const { owner, repo, pull_number, updated_at } = meta;
    const reqStart = Date.now();
    S.updateStriffButton({ loading: true, phase: " Fetching source...", tooltip: "Generating Striffs…" });
    S.cinfo?.("Striffs request (token)", { owner, repo, pull_number, updated_at });
    const resp = await S.bgRequest({
      type: "fetchStriffsWithToken",
      owner,
      repo,
      pull_number,
      updated_at,
      token,
    }, timeoutFor("bgToken", timeoutFor("message", 7000)));
    const durationMs = Date.now() - reqStart;
    S.cinfo?.("Striffs timings", resp?.timings || { type: "token", durationMs, note: "no timings payload from background" });
    return resp.json;
  }

  async function requestWithZips(meta) {
    const { updated_at } = meta;
    const reqStart = Date.now();
    S.updateStriffButton({ loading: true, phase: "Generating diagram...", tooltip: "Generating Striffs…" });
    const filterFiles = S.getFilterFilesFromNav();
    const { baseOwner, baseRepo, baseBranch, headOwner, headRepo, headBranch } = S.extractHeadBaseRefs();
    S.cinfo?.("Striffs request (zips)", {
      baseOwner, baseRepo, baseBranch, headOwner, headRepo, headBranch,
      filterFilesCount: filterFiles.length,
      filterFilesPreview: filterFiles.slice(0, 20)
    });
    const resp = await S.bgRequest({
      type: "generateStriffs",
      baseOwner, baseRepo, baseBranch,
      headOwner, headRepo, headBranch,
      filterFiles,
      updated_at,
    }, timeoutFor("bgGenerate", timeoutFor("message", 7000)));
    const durationMs = Date.now() - reqStart;
    S.cinfo?.("Striffs timings", resp?.timings || { type: "generate", durationMs, note: "no timings payload from background" });
    return resp.json;
  }

  function renderStriffsResult(result, updated_at, { fromCache = false } = {}) {
    const striffContainer = S.ensureStriffContainer();
    if (!S.isValidStriffsResult(result)) {
      throw new Error(result?.error || result?.message || "Invalid response.");
    }

    if (Array.isArray(result.striffs) && result.striffs.length === 0) {
      if (striffContainer) {
        striffContainer.innerHTML = `<div id="striffs-toast" role="status" aria-live="polite"></div>`;
      }
      S.updateStriffButton({ neutral: true, tooltip: "No changes were found", disabled: true });
      S.__striffsReady = false;
      S.__lastFetchedUpdatedAt = updated_at;
      S.__lastLoadSource = fromCache ? "cache" : "fresh";
      S.toast?.("No changes were found.", "neutral", { timeoutMs: 5000 });
      return;
    }

    if (striffContainer) {
      const rendered = S.renderStriffsInto(striffContainer, result);
      if (S.state?.isTooLarge?.()) {
        S.__striffsReady = false;
        S.updateStriffButton({ neutral: true, disabled: true, tooltip: "Diagram too large to render" });
        return;
      }
      if (!rendered) {
        cerr("Render returned false");
        throw new Error("Failed to render diagram.");
      }
      if (!fromCache) {
        writeCachedDiagram(result, updated_at);
        S.__lastLoadSource = "fresh";
      } else {
        S.__lastLoadSource = "cache";
      }
    }

    S.__striffsReady = true;
    S.__lastFetchedUpdatedAt = updated_at;
    S.updateStriffButton({ success: true, tooltip: "Striffs loaded. Click to view." });
  }

  S.autoFetchStriffs = async () => {
    const token = await S.getStoredToken();
    const meta = S.extractPRMetadata();
    const { updated_at } = meta;

    S.buildFilePathToDiffIdMapAsync?.(); // parallel, but safe

    try {
      let result = readCachedDiagram(updated_at);
      const fromCache = !!result;

      if (!result) {
        result = token ? await requestWithToken(token, meta) : await requestWithZips(meta);
        writeCachedDiagram(result, updated_at);
      }

      renderStriffsResult(result, updated_at, { fromCache });
      return true;
    } catch (err) {
      const message = err?.message || String(err);
      cerr("autoFetchStriffs error:", message, err);

      S.updateStriffButton({ failure: true, tooltip: message });
      S.__striffsReady = false;

      S.toast?.(message, "error", { timeoutMs: 5000 });
      return false;
    }
  };

  // ---------- UI Events ----------

  // Shared helpers used by initial boot + navigation boot
  S.waitForToolbar = S.waitForToolbar || async function waitForToolbar(maxMs = timeoutFor("waitForToolbar", 8000)) {
    const sleep = S.sleep || ((ms) => new Promise((r) => setTimeout(r, ms)));
    const start = Date.now();
    let toolbar = typeof S.getMainToolbar === 'function' ? S.getMainToolbar() : null;
    while (!toolbar && Date.now() - start < maxMs) {
      await sleep(120);
      toolbar = typeof S.getMainToolbar === 'function' ? S.getMainToolbar() : null;
    }
    return toolbar;
  };

  S.ensureSupportedExtensionsReady = S.ensureSupportedExtensionsReady || async function ensureSupportedExtensionsReady() {
    if (Array.isArray(S.__supportedExtensionsForUi) && S.__supportedExtensionsForUi.length > 0) return;
    if (typeof S.fetchSupportedExtensions !== 'function' || typeof S.registerSupportedExtensions !== 'function') return;
    try {
      const exts = await S.fetchSupportedExtensions();
      if (Array.isArray(exts)) {
        S.registerSupportedExtensions(exts);
      }
    } catch (err) {
      S.cwarn?.('languages check error', err);
    }
  };

  // File tree -> center the corresponding node in the diagram when Striffs view is visible
  registerDomListeners();

  // Focus flash (temporarily disabled: no visual highlight styling)
  S.flashFocus = (elem) => {
    try {
      if (!elem) return;
      // no-op
    } catch {}
  };

  S.centerOnElement = (svg, elem, pan, paddingFactor = 0.8, scaleAdjust = 1.0) => {
    try {
      const striffView = document.getElementById("striff-diagram-view") || svg.parentElement;
      const container = striffView.getBoundingClientRect();
      const bbox = elem.getBBox();
      let scale = Math.min(container.width / (bbox.width || 1), container.height / (bbox.height || 1)) * paddingFactor;
      scale = Math.max(scale * scaleAdjust, 0.1);
      pan.zoomAbs(0, 0, scale);
      const cx = bbox.x + bbox.width / 2;
      const cy = bbox.y + bbox.height / 2;
      const tx = container.width / 2 - cx * scale;
      const ty = container.height / 2 - cy * scale;
      pan.moveTo(tx, ty);
    } catch (e) { cwarn('centerOnElement skipped', e); }
  };

  window.addEventListener("pagehide", () => {
    S.teardownDomListeners();
    S.teardownNavListeners?.();
  }, { once: true });

  window.StriffsForceReload = async function () {
    const btn = document.getElementById("striffs-btn");
    if (!btn) return S.cwarn("Striffs button not found");

    S.__striffsReady = false;
    S.__lastFetchedUpdatedAt = null;
    S.__striffsSvg = null;
    S.__striffsPanzoom = null;
    S.__striffsPathToComponentId.clear();
    S.__striffsComponentIdToFile.clear();
    S.__lastPanState = null;

    try { localStorage.removeItem(S.cacheKey()); } catch {}

    const view = document.getElementById("striff-diagram-view");
    if (view) view.innerHTML = `<div id="striffs-toast" role="status" aria-live="polite"></div><p>Reloading…</p>`;

    S.updateStriffButton({ loading: true, tooltip: "Force reloading…", phase: "Bypassing cache..." });
    const ok = await S.autoFetchStriffs();
    if (ok && S.__striffsReady) {
      S.updateStriffButton({ success: true, tooltip: "Reloaded fresh." });
      S.showStriffView();
      document.getElementById("striff-diagram-view")?.scrollIntoView({ block: "start", behavior: "smooth" });
    }
  };

  // ---------- BOOT ----------
  const isPR = (p) => /\/[^/]+\/[^/]+\/pull\/\d+/.test(p);
  const isPRFiles = (p) => /\/[^/]+\/[^/]+\/pull\/\d+\/files/.test(p);
  const isPRList = (p) => /\/[^/]+\/[^/]+\/pulls/.test(p);
  S.isPRPath = S.isPRPath || isPR;
  S.isPRFilesPath = S.isPRFilesPath || isPRFiles;
  S.isPRListPath = S.isPRListPath || isPRList;

  S.setDefaultButtonIfIdle = () => {
    S.revealToolbarButtons?.();
    const last = S.__lastStriffsButtonState || {};
    if (last.loading || last.success || last.failure) return;
    S.updateStriffButton({ tooltip: "Click to generate Striffs" });
  };

  const relevantPage = isPR(location.pathname);
  const onFilesPage = isPRFiles(location.pathname);
  if (!relevantPage) return;

  console.log('[Striffs] content script boot', location.href);

  try {
    S.addSpinAnimation?.();
  } catch (e) {
    S.__striffsErrors = S.__striffsErrors || [];
    S.__striffsErrors.push({ where: 'addSpinAnimation', error: String(e) });
    console.error('[Striffs] addSpinAnimation failed', e);
  }

  if (!onFilesPage) {
    return;
  }

  const toolbar = await S.waitForToolbar?.();
  if (toolbar) S.mountMainBarButtons?.();

  S.setDefaultButtonIfIdle();

  await S.ensureSupportedExtensionsReady?.();

  const filesRoot = await S.waitForFilesRoot();
  if (!filesRoot) {
    S.cwarn?.('Files root not found; skipping initial boot');
    return;
  }
  S.buildFilePathToDiffIdMapAsync?.();
  S.primeDiagramFromCache();

  S.setActiveButtons("diffs");
  S.showDiffView();
  S.saveActiveTab("diffs");
})();

(() => {
  const S = (window.Striffs = window.Striffs || {});
  let lastPath = location.pathname;
  let navIntervalId = null;

  const isPR = S.isPRPath || ((p) => /\/[^/]+\/[^/]+\/pull\/\d+/.test(p));
  const isPRFiles = S.isPRFilesPath || ((p) => /\/[^/]+\/[^/]+\/pull\/\d+\/files/.test(p));

  async function bootIfNeeded() {
    if (!isPR(location.pathname)) return;

    if (location.pathname === lastPath && !isPRFiles(location.pathname)) return;
    lastPath = location.pathname;

    try {
      if (!isPRFiles(location.pathname)) return;

      S.addSpinAnimation?.();
      await S.waitForToolbar?.();
      S.mountMainBarButtons?.();
      S.setDefaultButtonIfIdle?.();
      await S.ensureSupportedExtensionsReady?.();

      const filesRoot = await S.waitForFilesRoot?.();
      if (!filesRoot) return;

      S.buildFilePathToDiffIdMapAsync?.();

      S.primeDiagramFromCache?.();
      S.setActiveButtons?.("diffs");
      S.showDiffView?.();
      S.saveActiveTab?.("diffs");
    } catch (e) {
      console.warn('[Striffs] nav boot skipped', e);
    }
  }

  S.teardownNavListeners = function teardownNavListeners() {
    if (!S.__navListenersRegistered) return;
    document.removeEventListener('turbo:load', bootIfNeeded);
    document.removeEventListener('turbo:render', bootIfNeeded);
    document.removeEventListener('pjax:end', bootIfNeeded);
    window.removeEventListener('popstate', bootIfNeeded);
    window.removeEventListener('striffs:navigate', bootIfNeeded);
    if (S.__origPushState) history.pushState = S.__origPushState;
    if (S.__origReplaceState) history.replaceState = S.__origReplaceState;
    if (navIntervalId) {
      clearInterval(navIntervalId);
      navIntervalId = null;
    }
    S.__navListenersRegistered = false;
  };

  function registerNavListeners() {
    if (S.__navListenersRegistered) return;

    document.addEventListener('turbo:load', bootIfNeeded);
    document.addEventListener('turbo:render', bootIfNeeded);
    document.addEventListener('pjax:end', bootIfNeeded);

    if (!S.__origPushState) S.__origPushState = history.pushState;
    if (!S.__origReplaceState) S.__origReplaceState = history.replaceState;

    const fireNav = () => window.dispatchEvent(new Event('striffs:navigate'));
    history.pushState = function () { const r = S.__origPushState.apply(this, arguments); fireNav(); return r; };
    history.replaceState = function () { const r = S.__origReplaceState.apply(this, arguments); fireNav(); return r; };

    window.addEventListener('popstate', bootIfNeeded);
    window.addEventListener('striffs:navigate', bootIfNeeded);

    navIntervalId = setInterval(() => {
      if (location.pathname !== lastPath) bootIfNeeded();
    }, 800);

    S.__navListenersRegistered = true;
  }

  registerNavListeners();
})();
